### ISSUE TITLE
[Feature]: Contests

### ISSUE THREAD

**Issue by fu050409** [swpu-acm/online-judge#37]
Support create, update (includes add, remove problems from contest), delete and method for user to participant in a contest.

**Comment by fu050409** [comment]
@HsiangNianian

**Comment by HsiangNianian** [comment]
- [ ] create
- [ ] add
- [ ] remove/delete
- [ ] update
- [ ] participate

**Comment by fu050409** [comment]
@HsiangNianian You can send a pull request and mark it `WIP` (or tags with), we can review the codes instantly so that there wont be any misunderstandings :D
